a=float(input("a="))
b=float(input("b="))
print(a,"+",b,"=",a+b)
print(a,"-",b,"=",a-b)
print(a,"*",b,"=",a*b)
print(a,"//",b,"=",a//b)
print(a,"**",b,"=",a**b)
print(a,"%",b,"=",a%b)
if a>b :
    print(a,">",b)
elif a==b :
    print(a,"=",b)
else :
    print(a,"<",b)
print(a,"AND",b)
print(a,"OR",b)
print(a,"XOR",b)
print("NOT",a,"==",b)
print(a,"dich phai 1 don vi:",a*10)
print(a,"dich trai 1 don vi:",a/10)